name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile and build
      run: |
        gcc -o password password.c

    - name: Run tests
      run: |
        ./password

    # Optionally, you can add more steps for additional checks or tests here
